/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;
import java.util.logging.Level;

/**
 *
 * @author nttlk
 */
public class Dailyy extends javax.swing.JFrame {
    
    // ตั้งชื่อไฟล์ CSV สำหรับบันทึกโน้ต
    private static final String NOTES_FILE = "daily_notes.csv";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dailyy.class.getName());

    /**
     * Creates new form Dailyy
     */
    public Dailyy() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabel1.setText("Daily");
        
        // ******* ส่วนของการอ่านไฟล์ users.csv (ยังคงไว้ แต่ไม่สมบูรณ์ในการใช้งานจริง) *******
        // ในการใช้งานจริง, โค้ดส่วนนี้ควรอยู่ในฟังก์ชัน Login และต้องการตัวแปรสำหรับรับค่าจาก GUI
        // เพื่อนำมาเปรียบเทียบกับ fileUsername และ filePassword 
        try (BufferedReader br = new BufferedReader(new FileReader("users.csv"))) {
            String line;
            boolean userFound = false;
            while ((line = br.readLine()) != null) {
                String[] userData = line.split(",");
                if (userData.length >= 3) {
                    String fileGmail = userData[0];
                    String fileUsername = userData[1];
                    String filePassword = userData[2];

                    // ส่วนที่ต้องการค่าจาก JTextField เพื่อเปรียบเทียบ:
                    // if (fileUsername.equals(usernameInput) && filePassword.equals(passwordInput)) {
                    //     userFound = true;
                    //     break;
                    // }
                }
            }
            // ส่วนที่ถูกแก้ไขให้สมบูรณ์ขึ้น (ในกรณีนี้คือเอาโค้ดที่ไม่สมบูรณ์ออก)
        } catch (IOException ex) {
            // ex.printStackTrace(); // ไม่แสดง stack trace ใน GUI ที่เป็นทางการ
            // logger.log(Level.WARNING, "Cannot find or read users.csv", ex);
            // javax.swing.JOptionPane.showMessageDialog(this, "ไม่พบไฟล์ users.csv");
            // ไม่ต้อง return; เพราะต้องการให้ GUI เปิดได้แม้ไม่มีไฟล์
        }
        // ******* สิ้นสุดส่วนของการอ่านไฟล์ *******

        jButton1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jButton1.setText("Cancel");

        jButton2.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jButton2.setText("Notes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        saveDailyNote();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * ฟังก์ชันสำหรับบันทึกข้อมูลจาก jTextField1 ลงในไฟล์ CSV.
     * โน้ตจะถูกต่อท้ายไฟล์เดิม (append mode).
     * รูปแบบที่บันทึก: "วันที่และเวลาปัจจุบัน,ข้อความใน jTextField1"
     */
    private void saveDailyNote() {
        // ดึงข้อความจาก JTextField
        String note = jTextField1.getText().trim();
        
        // ไม่บันทึกถ้าข้อความว่างเปล่า
        if (note.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "กรุณาป้อนข้อมูลก่อนบันทึก!");
            return;
        }

        // สร้าง Date/Time สำหรับบันทึก
        String timestamp = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());
        
        // จัดรูปแบบข้อมูลเป็น CSV: "timestamp","note"
        // ใช้ double quotes ครอบข้อความเพื่อจัดการกับเครื่องหมายจุลภาค (,) ภายในโน้ต
        String csvLine = String.format("\"%s\",\"%s\"", timestamp, note.replace("\"", "\"\""));

        // เขียนข้อมูลลงในไฟล์ CSV (ใช้ 'true' ใน FileWriter เพื่อให้เป็นการต่อท้ายไฟล์)
        try (PrintWriter pw = new PrintWriter(new FileWriter(NOTES_FILE, true))) {
            pw.println(csvLine);
            javax.swing.JOptionPane.showMessageDialog(this, "บันทึกโน้ตสำเร็จแล้วในไฟล์: " + NOTES_FILE);
            // ล้างช่องป้อนข้อมูลหลังจากบันทึก
            jTextField1.setText(""); 
        } catch (IOException ex) {
            logger.log(Level.SEVERE, "Error writing to CSV file", ex);
            javax.swing.JOptionPane.showMessageDialog(this, "เกิดข้อผิดพลาดในการบันทึกไฟล์: " + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dailyy().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}