
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JDialog;
import javax.swing.border.LineBorder;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class CreateDialy extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateDialy.class.getName());
    private Home home;
    private String username;
     private String gmail;
     private String password;
    /**
     * Creates new form CreateDialog
     */
    public CreateDialy(Home home, String Gmail,  String Username, String Password) {
        this.home = home;
        this.username = Username;
        this.gmail = Gmail;
        this.password = Password;
        this.setLocationRelativeTo(null);
        initComponents();
        
        setPlaceholder(DateDD, "DD");
        setPlaceholder(DateDM, "MM");
        setPlaceholder(DateDY, "YYYY");
        
        setNumberLimit(DateDD, 2);
        setNumberLimit(DateDM, 2);
        setNumberLimit(DateDY, 4);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CONFIRM = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();
        Dialy = new javax.swing.JLabel();
        Topic = new javax.swing.JLabel();
        TopicD = new javax.swing.JTextField();
        Date = new javax.swing.JLabel();
        NotiTopicD = new javax.swing.JLabel();
        DateDD = new javax.swing.JTextField();
        NotiDateD = new javax.swing.JLabel();
        DateDM = new javax.swing.JTextField();
        DateDY = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ContentD = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 245));

        jPanel2.setBackground(new java.awt.Color(241, 255, 255));

        CONFIRM.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        CONFIRM.setForeground(new java.awt.Color(255, 204, 0));
        CONFIRM.setText("CONFIRM");
        CONFIRM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CONFIRMMouseClicked(evt);
            }
        });

        BACK.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        BACK.setForeground(new java.awt.Color(0, 102, 255));
        BACK.setText("BACK");
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BACK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(CONFIRM)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CONFIRM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BACK, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
                .addContainerGap())
        );

        Dialy.setFont(new java.awt.Font("STHupo", 0, 65)); // NOI18N
        Dialy.setForeground(new java.awt.Color(255, 0, 0));
        Dialy.setText("DIALY");

        Topic.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        Topic.setText("TOPIC");

        TopicD.setBackground(new java.awt.Color(246, 249, 249));
        TopicD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        TopicD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopicDActionPerformed(evt);
            }
        });

        Date.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        Date.setText("DATE");

        NotiTopicD.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        NotiTopicD.setForeground(new java.awt.Color(204, 0, 0));

        DateDD.setBackground(new java.awt.Color(246, 249, 249));
        DateDD.setForeground(new java.awt.Color(153, 153, 153));
        DateDD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DateDD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        DateDD.setMinimumSize(new java.awt.Dimension(64, 25));
        DateDD.setPreferredSize(new java.awt.Dimension(64, 25));
        DateDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateDDActionPerformed(evt);
            }
        });

        NotiDateD.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        NotiDateD.setForeground(new java.awt.Color(204, 0, 51));

        DateDM.setBackground(new java.awt.Color(246, 249, 249));
        DateDM.setForeground(new java.awt.Color(153, 153, 153));
        DateDM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DateDM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        DateDM.setMinimumSize(new java.awt.Dimension(64, 25));
        DateDM.setPreferredSize(new java.awt.Dimension(64, 25));
        DateDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateDMActionPerformed(evt);
            }
        });

        DateDY.setBackground(new java.awt.Color(246, 249, 249));
        DateDY.setForeground(new java.awt.Color(153, 153, 153));
        DateDY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DateDY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        DateDY.setMinimumSize(new java.awt.Dimension(64, 25));
        DateDY.setPreferredSize(new java.awt.Dimension(64, 25));
        DateDY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateDYActionPerformed(evt);
            }
        });

        ContentD.setBackground(new java.awt.Color(255, 255, 243));
        ContentD.setColumns(20);
        ContentD.setRows(5);
        ContentD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jScrollPane1.setViewportView(ContentD);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(Dialy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(NotiTopicD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TopicD, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(Topic, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NotiDateD, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DateDD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateDM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateDY, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dialy, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Topic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TopicD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(NotiTopicD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date)
                    .addComponent(DateDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateDY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(NotiDateD)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Home home = new Home(gmail,username,password);
        home.setVisible(true);
        home.pack();
        home.setLocationRelativeTo(null); //
        home.setDefaultCloseOperation(JDialog.EXIT_ON_CLOSE);
    }//GEN-LAST:event_BACKMouseClicked

    private void TopicDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopicDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TopicDActionPerformed

    private void CONFIRMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONFIRMMouseClicked
        // TODO add your handling code here:
        String topicD = TopicD.getText().trim();
        String contentD = ContentD.getText();
        String dateDD = DateDD.getText().trim();
        String dateDM = DateDM.getText().trim();
        String dateDY = DateDY.getText().trim();
        
        NotiTopicD.setText("");
        NotiDateD.setText("");
        
        TopicD.setBorder(new LineBorder(Color.GRAY, 1));
        DateDD.setBorder(new LineBorder(Color.GRAY, 1));
        DateDM.setBorder(new LineBorder(Color.GRAY, 1));
        DateDY.setBorder(new LineBorder(Color.GRAY, 1));
        
        boolean hasError = false;
        boolean ddEmpty = dateDD.equals("DD");
        boolean dmEmpty = dateDM.equals("MM");
        boolean dyEmpty = dateDY.equals("YYYY");
        
        if (topicD.isEmpty()) {
            NotiTopicD.setText("Please enter a topic.");
            TopicD.setBorder(new LineBorder(Color.RED, 1));
            hasError = true;
        }
        if (ddEmpty || dmEmpty || dyEmpty) {
            NotiDateD.setText("Please put a date.");
            DateDD.setBorder(new LineBorder(Color.RED, 1));
            DateDM.setBorder(new LineBorder(Color.RED, 1));
            DateDY.setBorder(new LineBorder(Color.RED, 1));
            hasError = true;
        } else {
            if (!dateDD.matches("\\d{1,2}") || !dateDM.matches("\\d{1,2}") || !dateDY.matches("\\d{4}")) {
                NotiDateD.setText("Invalid date.");
                DateDD.setBorder(new LineBorder(Color.RED, 1));
                DateDM.setBorder(new LineBorder(Color.RED, 1));
                DateDY.setBorder(new LineBorder(Color.RED, 1));
                hasError = true;
            } else {
                try {int day = Integer.parseInt(dateDD);
                     int month = Integer.parseInt(dateDM);
                     int year = Integer.parseInt(dateDY);

                     java.time.LocalDate.of(year, month, day);
                
                } catch (Exception e) {
                     NotiDateD.setText("Invalid date.");
                     DateDD.setBorder(new LineBorder(Color.RED, 1));
                     DateDM.setBorder(new LineBorder(Color.RED, 1));
                     DateDY.setBorder(new LineBorder(Color.RED, 1));
                     hasError = true;
                }
            }
         
        if(hasError){
            return;
        }
        
        String filePath = "Data/dialy.csv";
        
        try (FileWriter fw = new FileWriter(filePath, true); 
             BufferedWriter bw = new BufferedWriter(fw);
             PrintWriter out = new PrintWriter(bw))
        {

            out.println(topicD + "," + dateDD + "/" + dateDM + "/" + dateDY + "," + contentD);
            
            this.dispose();
            home.setVisible(true);

        } catch (IOException ex) {
            ex.printStackTrace();
        }
        }   
    }//GEN-LAST:event_CONFIRMMouseClicked

    private void DateDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateDDActionPerformed

    private void DateDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateDMActionPerformed

    private void DateDYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateDYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateDYActionPerformed

    private void setPlaceholder(javax.swing.JTextField field, String placeholder) {
        field.setText(placeholder);
        field.setForeground(Color.GRAY);

        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
            if (field.getText().equals(placeholder)) {
                field.setText("");
                field.setForeground(Color.BLACK);
               }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
            if (field.getText().isEmpty()) {
                field.setText(placeholder);
                field.setForeground(Color.GRAY);
               }
            }
        });
    }
    
    private void setNumberLimit(javax.swing.JTextField field, int limit) {
        field.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
            char c = e.getKeyChar();
            if (!Character.isDigit(c) || field.getText().length() >= limit) {
                e.consume();
               }
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Home home = new Home("Gmail","Username","Password");
            new CreateDialy(home,"Gmail","Username","Password").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JLabel CONFIRM;
    private javax.swing.JTextArea ContentD;
    private javax.swing.JLabel Date;
    private javax.swing.JTextField DateDD;
    private javax.swing.JTextField DateDM;
    private javax.swing.JTextField DateDY;
    private javax.swing.JLabel Dialy;
    private javax.swing.JLabel NotiDateD;
    private javax.swing.JLabel NotiTopicD;
    private javax.swing.JLabel Topic;
    private javax.swing.JTextField TopicD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
