/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import javax.swing.JDialog;
import javax.swing.border.LineBorder;
/**
 *
 * @author user
 */
public class Dialy extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dialy.class.getName());
    private Home home;
    private String username;
    private String gmail;
    private String password;
    
    
    public Dialy(Home home, String Gmail, String Username, String Password) {
        
        this.home = home;
        this.username = Username;
        this.gmail = Gmail;
        this.password = Password;
        
        initComponents();
        
        setPlaceholder(FindD, "DD");
        setPlaceholder(FindM, "MM");
        setPlaceholder(FindY, "YYYY");
        
        setNumberLimit(FindD, 2);
        setNumberLimit(FindM, 2);
        setNumberLimit(FindY, 4);
        
        //Topic4.setVisible(false);
        
        //DialyFB1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Dialy = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();
        FindD = new javax.swing.JTextField();
        FindM = new javax.swing.JTextField();
        FindY = new javax.swing.JTextField();
        FineDate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NotiFindD = new javax.swing.JLabel();
        DialyFB1 = new javax.swing.JPanel();
        TOPIC1 = new javax.swing.JLabel();
        Topic1 = new javax.swing.JLabel();
        DATE1 = new javax.swing.JLabel();
        Date1 = new javax.swing.JLabel();
        DialyFB4 = new javax.swing.JPanel();
        TOPIC4 = new javax.swing.JLabel();
        Topic4 = new javax.swing.JLabel();
        DATE4 = new javax.swing.JLabel();
        Date4 = new javax.swing.JLabel();
        DialyFB5 = new javax.swing.JPanel();
        TOPIC5 = new javax.swing.JLabel();
        Topic5 = new javax.swing.JLabel();
        DATE5 = new javax.swing.JLabel();
        Date5 = new javax.swing.JLabel();
        DialyFB6 = new javax.swing.JPanel();
        TOPIC6 = new javax.swing.JLabel();
        Topic6 = new javax.swing.JLabel();
        DATE6 = new javax.swing.JLabel();
        Date6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 250, 250));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        Dialy.setFont(new java.awt.Font("STHupo", 0, 40)); // NOI18N
        Dialy.setForeground(new java.awt.Color(255, 0, 0));
        Dialy.setText("DIALY");

        BACK.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        BACK.setForeground(new java.awt.Color(0, 102, 255));
        BACK.setText("BACK");
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BACK)
                .addGap(107, 107, 107)
                .addComponent(Dialy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dialy, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        FindD.setBackground(new java.awt.Color(255, 255, 243));
        FindD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FindD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        FindD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindDActionPerformed(evt);
            }
        });

        FindM.setBackground(new java.awt.Color(255, 255, 243));
        FindM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FindM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        FindM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindMActionPerformed(evt);
            }
        });

        FindY.setBackground(new java.awt.Color(255, 255, 243));
        FindY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FindY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        FindY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindYActionPerformed(evt);
            }
        });

        FineDate.setFont(new java.awt.Font("STHupo", 0, 20)); // NOI18N
        FineDate.setForeground(new java.awt.Color(0, 102, 255));
        FineDate.setText("DATE");

        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NotiFindD.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        NotiFindD.setForeground(new java.awt.Color(255, 0, 0));

        DialyFB1.setBackground(new java.awt.Color(255, 255, 255));

        TOPIC1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TOPIC1.setForeground(new java.awt.Color(255, 102, 0));
        TOPIC1.setText("TOPIC");

        Topic1.setForeground(new java.awt.Color(0, 102, 255));

        DATE1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DATE1.setForeground(new java.awt.Color(0, 204, 51));
        DATE1.setText("DATE");

        Date1.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout DialyFB1Layout = new javax.swing.GroupLayout(DialyFB1);
        DialyFB1.setLayout(DialyFB1Layout);
        DialyFB1Layout.setHorizontalGroup(
            DialyFB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialyFB1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialyFB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DialyFB1Layout.createSequentialGroup()
                        .addComponent(TOPIC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Topic1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DialyFB1Layout.createSequentialGroup()
                        .addComponent(DATE1)
                        .addGap(18, 18, 18)
                        .addComponent(Date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        DialyFB1Layout.setVerticalGroup(
            DialyFB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialyFB1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialyFB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TOPIC1)
                    .addComponent(Topic1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialyFB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DATE1)
                    .addComponent(Date1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DialyFB4.setBackground(new java.awt.Color(255, 255, 255));

        TOPIC4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TOPIC4.setForeground(new java.awt.Color(255, 102, 0));
        TOPIC4.setText("TOPIC");

        Topic4.setForeground(new java.awt.Color(0, 102, 255));
        Topic4.setText("TOPIC");

        DATE4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DATE4.setForeground(new java.awt.Color(0, 204, 51));
        DATE4.setText("DATE");

        Date4.setForeground(new java.awt.Color(0, 102, 255));
        Date4.setText("DATE");

        javax.swing.GroupLayout DialyFB4Layout = new javax.swing.GroupLayout(DialyFB4);
        DialyFB4.setLayout(DialyFB4Layout);
        DialyFB4Layout.setHorizontalGroup(
            DialyFB4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialyFB4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialyFB4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DialyFB4Layout.createSequentialGroup()
                        .addComponent(TOPIC4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Topic4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DialyFB4Layout.createSequentialGroup()
                        .addComponent(DATE4)
                        .addGap(18, 18, 18)
                        .addComponent(Date4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        DialyFB4Layout.setVerticalGroup(
            DialyFB4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialyFB4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialyFB4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TOPIC4)
                    .addComponent(Topic4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialyFB4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DATE4)
                    .addComponent(Date4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DialyFB5.setBackground(new java.awt.Color(255, 255, 255));

        TOPIC5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TOPIC5.setForeground(new java.awt.Color(255, 102, 0));
        TOPIC5.setText("TOPIC");

        Topic5.setForeground(new java.awt.Color(0, 102, 255));
        Topic5.setText("TOPIC");

        DATE5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DATE5.setForeground(new java.awt.Color(0, 204, 51));
        DATE5.setText("DATE");

        Date5.setForeground(new java.awt.Color(0, 102, 255));
        Date5.setText("DATE");

        javax.swing.GroupLayout DialyFB5Layout = new javax.swing.GroupLayout(DialyFB5);
        DialyFB5.setLayout(DialyFB5Layout);
        DialyFB5Layout.setHorizontalGroup(
            DialyFB5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialyFB5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialyFB5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DialyFB5Layout.createSequentialGroup()
                        .addComponent(TOPIC5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Topic5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DialyFB5Layout.createSequentialGroup()
                        .addComponent(DATE5)
                        .addGap(18, 18, 18)
                        .addComponent(Date5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        DialyFB5Layout.setVerticalGroup(
            DialyFB5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialyFB5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialyFB5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TOPIC5)
                    .addComponent(Topic5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialyFB5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DATE5)
                    .addComponent(Date5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DialyFB6.setBackground(new java.awt.Color(255, 255, 255));

        TOPIC6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TOPIC6.setForeground(new java.awt.Color(255, 102, 0));
        TOPIC6.setText("TOPIC");

        Topic6.setForeground(new java.awt.Color(0, 102, 255));
        Topic6.setText("TOPIC");

        DATE6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DATE6.setForeground(new java.awt.Color(0, 204, 51));
        DATE6.setText("DATE");

        Date6.setForeground(new java.awt.Color(0, 102, 255));
        Date6.setText("DATE");

        javax.swing.GroupLayout DialyFB6Layout = new javax.swing.GroupLayout(DialyFB6);
        DialyFB6.setLayout(DialyFB6Layout);
        DialyFB6Layout.setHorizontalGroup(
            DialyFB6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialyFB6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialyFB6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DialyFB6Layout.createSequentialGroup()
                        .addComponent(TOPIC6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Topic6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DialyFB6Layout.createSequentialGroup()
                        .addComponent(DATE6)
                        .addGap(18, 18, 18)
                        .addComponent(Date6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        DialyFB6Layout.setVerticalGroup(
            DialyFB6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialyFB6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialyFB6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TOPIC6)
                    .addComponent(Topic6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialyFB6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DATE6)
                    .addComponent(Date6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DialyFB6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DialyFB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DialyFB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DialyFB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FineDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NotiFindD)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FindD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FindM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FindY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FindD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FineDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindY, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(NotiFindD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DialyFB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DialyFB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DialyFB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DialyFB6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Home home = new Home(gmail,username,password);
        home.setVisible(true);
        home.pack();
        home.setLocationRelativeTo(null); //
        home.setDefaultCloseOperation(JDialog.EXIT_ON_CLOSE);
    }//GEN-LAST:event_BACKMouseClicked

    private void FindDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindDActionPerformed

    private void FindMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindMActionPerformed

    private void FindYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindYActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String findD = FindD.getText().trim();
        String findM = FindM.getText().trim();
        String findY = FindY.getText().trim();
       
        
        
        NotiFindD.setText("");
    
        FindD.setBorder(new LineBorder(Color.GRAY, 1));
        FindM.setBorder(new LineBorder(Color.GRAY, 1));
        FindY.setBorder(new LineBorder(Color.GRAY, 1));
        
        boolean hasError = false;
        boolean FDEmpty = findD.equals("DD") || findM.equals("MM") || findY.equals("YYYY");
        
        if (FDEmpty) {
            NotiFindD.setText("Please enter date.");
            FindD.setBorder(new LineBorder(Color.RED, 1));
            FindM.setBorder(new LineBorder(Color.RED, 1));
            FindY.setBorder(new LineBorder(Color.RED, 1));
            hasError = true;
        }
        if(hasError){
            return;
        }
        int d, m, y;
        try {
             d = Integer.parseInt(findD);
             m = Integer.parseInt(findM);
             y = Integer.parseInt(findY);
             LocalDate date = LocalDate.of(y, m, d);
        } catch (Exception e) {
                 NotiFindD.setText("Invalid date.");
                 return;
        }
        File file = new File("Data/dialy.csv");
             if (!file.exists()) {
             //NotiFindD.setText("No data file found.");
             return;
             }
             
        boolean found = false;
        
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
             String line;
             while ((line = br.readLine()) != null) {
                 
                    String[] parts = line.split(",");
                    if (parts.length >= 2) {
                        String topic = parts[0].trim();
                        String dateStr = parts[1].trim();
                        
                        String[] dateParts = dateStr.split("/");
                        if (dateParts.length == 3) {
                            String dateD = dateParts[0].trim();
                            String dateM = dateParts[1].trim();
                            String dateY = dateParts[2].trim();

                    if (dateD.equals(findD) && dateM.equals(findM) && dateY.equals(findY)) {
                        Topic1.setText(topic);
                        Date1.setText(dateD + "/" + dateM + "/" + dateY);
                        found = true;
                        DialyFB1.setVisible(true);
                        break;
                    }
                    }
                }
             }
        } catch (IOException e) {
                 e.printStackTrace();
                 //NotiFindD.setText("Error reading file.");
                 //return;
        }

        if (!found) {
        //NotiFindD.setText("No event found for that date.");
        Topic1.setText("");
        Date1.setText("");
        }
    
    }//GEN-LAST:event_jButton1MouseClicked

    private void setPlaceholder(javax.swing.JTextField field, String placeholder) {
        field.setText(placeholder);
        field.setForeground(Color.GRAY);

        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
            if (field.getText().equals(placeholder)) {
                field.setText("");
                field.setForeground(Color.BLACK);
               }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
            if (field.getText().isEmpty()) {
                field.setText(placeholder);
                field.setForeground(Color.GRAY);
               }
            }
        });
    }
    
    private void setNumberLimit(javax.swing.JTextField field, int limit) {
        field.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
            char c = e.getKeyChar();
            if (!Character.isDigit(c) || field.getText().length() >= limit) {
                e.consume();
               }
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Home home = new Home("Gmail", "Username", "Password");
            new Dialy(home,"Gmail","Username","Password").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JLabel DATE1;
    private javax.swing.JLabel DATE4;
    private javax.swing.JLabel DATE5;
    private javax.swing.JLabel DATE6;
    private javax.swing.JLabel Date1;
    private javax.swing.JLabel Date4;
    private javax.swing.JLabel Date5;
    private javax.swing.JLabel Date6;
    private javax.swing.JLabel Dialy;
    private javax.swing.JPanel DialyFB1;
    private javax.swing.JPanel DialyFB4;
    private javax.swing.JPanel DialyFB5;
    private javax.swing.JPanel DialyFB6;
    private javax.swing.JTextField FindD;
    private javax.swing.JTextField FindM;
    private javax.swing.JTextField FindY;
    private javax.swing.JLabel FineDate;
    private javax.swing.JLabel NotiFindD;
    private javax.swing.JLabel TOPIC1;
    private javax.swing.JLabel TOPIC4;
    private javax.swing.JLabel TOPIC5;
    private javax.swing.JLabel TOPIC6;
    private javax.swing.JLabel Topic1;
    private javax.swing.JLabel Topic4;
    private javax.swing.JLabel Topic5;
    private javax.swing.JLabel Topic6;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
