
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author user
 */
public class EorDDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EorDDialog.class.getName());
    private String username;
    private Home home;
    private NotiFrame noti;
    private JFrame parent;
    private String gmail;
    private String password;
    /**
     * Creates new form EorD
     */
    public EorDDialog(java.awt.Frame parent, String Gmail, String Username, String Password, boolean modal) {
        super(parent, modal);
        if (parent instanceof Home) {
        this.home = (Home) parent;
        }
        
        //this.parent = (JFrame) parent;
        this.username = Username;
        this.gmail = Gmail ;
        this.password = Password;
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Event = new javax.swing.JButton();
        Dialy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(193, 221, 249));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        Event.setBackground(new java.awt.Color(255, 255, 204));
        Event.setFont(new java.awt.Font("STHupo", 0, 33)); // NOI18N
        Event.setForeground(new java.awt.Color(0, 102, 255));
        Event.setText("E");
        Event.setMaximumSize(new java.awt.Dimension(45, 45));
        Event.setMinimumSize(new java.awt.Dimension(45, 45));
        Event.setPreferredSize(new java.awt.Dimension(45, 45));
        Event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventActionPerformed(evt);
            }
        });

        Dialy.setBackground(new java.awt.Color(255, 255, 204));
        Dialy.setFont(new java.awt.Font("STHupo", 0, 33)); // NOI18N
        Dialy.setForeground(new java.awt.Color(255, 0, 0));
        Dialy.setText("D");
        Dialy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DialyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dialy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Event, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Event, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dialy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventActionPerformed
        // TODO add your handling code here:
        /*CreateEvent createEvent = new CreateEvent(username);
        createEvent.setVisible(true);
        this.setVisible(false);*/
        this.dispose();
        home.dispose();
        CreateEvent event = new CreateEvent(home,gmail,username,password) ;
        event.setVisible(true);
        
        /*if (getParent() instanceof Home) {
           Home home = (Home) getParent();
           home.refreshDayLeft();
           home.revalidate();
           home.repaint();
        }*/
        
        event.pack();
        event.setLocationRelativeTo(null);
        //event.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_EventActionPerformed

    private void DialyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DialyActionPerformed
        // TODO add your handling code here:
        this.dispose();
        home.dispose();
        CreateDialy dialy = new CreateDialy(home,gmail,username,password) ;
        dialy.setVisible(true);
        dialy.pack();
        dialy.setLocationRelativeTo(null);
        dialy.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_DialyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EorDDialog dialog = new EorDDialog(new javax.swing.JFrame(),"Gmail","Username","Password", true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dialy;
    private javax.swing.JButton Event;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
