
import java.awt.Dialog;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());
    private final String username;
    private final String gmail;
    private final String password ;
    private Home home;
    private EorDDialog eord;
    boolean eordVisible = false;
    private SettingDialog setting;
    boolean settingVisible = false;
    
    private int count;
    /**
     * Creates new form Home
     * 
     * @param Gmail
     * @param Username
     * @param Password
     */
    public Home(String Gmail, String Username, String Password) {
        initComponents();
        this.home = home;
        this.username = Username;
        this.gmail = Gmail;
        this.password = Password ;
        this.setLocationRelativeTo(null);
        
        Notification();
        
        EDayLeft();
        
        DayLeftBox1.setText("00");
        DayLeftBox2.setText("00");
        DayLeftBox3.setText("00");
        DayLeftBox4.setText("00");
        DayLeftBox5.setText("00");
        DayLeftBox6.setText("00");
        
        TOPICbox1.setText("TOPIC") ;
        TOPICbox2.setText("TOPIC") ;
        TOPICbox3.setText("TOPIC") ;
        TOPICbox4.setText("TOPIC") ;
        TOPICbox5.setText("TOPIC") ;
        TOPICbox6.setText("TOPIC") ;
        
        TopicEShow1.setText("Topic");
        
        Datebox1.setText("DD/MM/YYYY") ;
        Datebox2.setText("DD/MM/YYYY") ;
        Datebox3.setText("DD/MM/YYYY") ;
        Datebox4.setText("DD/MM/YYYY") ;
        Datebox5.setText("DD/MM/YYYY") ;
        Datebox6.setText("DD/MM/YYYY") ;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CMText = new javax.swing.JLabel();
        EventText = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        TOPICbox1 = new javax.swing.JLabel();
        Datebox1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        dayleftbox1 = new javax.swing.JLabel();
        DayLeftBox1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        DayLeftBox2 = new javax.swing.JLabel();
        dayleftbox2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        DayLeftBox3 = new javax.swing.JLabel();
        dayleftbox3 = new javax.swing.JLabel();
        Datebox4 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        DayLeftBox6 = new javax.swing.JLabel();
        dayleftbox6 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        DayLeftBox5 = new javax.swing.JLabel();
        dayleftbox5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        dayleftbox4 = new javax.swing.JLabel();
        DayLeftBox4 = new javax.swing.JLabel();
        TOPICbox4 = new javax.swing.JLabel();
        TOPICbox2 = new javax.swing.JLabel();
        Datebox2 = new javax.swing.JLabel();
        TOPICbox3 = new javax.swing.JLabel();
        Datebox3 = new javax.swing.JLabel();
        Datebox6 = new javax.swing.JLabel();
        Datebox5 = new javax.swing.JLabel();
        TOPICbox6 = new javax.swing.JLabel();
        TOPICbox5 = new javax.swing.JLabel();
        moreE = new javax.swing.JLabel();
        moreD = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TopicEShow1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DateEShow1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TopicEShow2 = new javax.swing.JLabel();
        DateEShow2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DateEShow3 = new javax.swing.JLabel();
        TopicEShow3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 700));
        jPanel1.setRequestFocusEnabled(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setFont(new java.awt.Font("STHupo", 0, 70)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("TUDU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(193, 221, 249));
        jPanel3.setForeground(new java.awt.Color(153, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/pen.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/bell.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/A0FE83E8-F989-4FB5-8051-28C980EA177C.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/home.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CMText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CMText.setForeground(new java.awt.Color(255, 102, 0));
        CMText.setText("Coming soon");

        EventText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EventText.setForeground(new java.awt.Color(51, 102, 255));
        EventText.setText("Events in");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 124, 79)));
        jPanel4.setForeground(new java.awt.Color(79, 124, 79));

        jPanel5.setBackground(new java.awt.Color(225, 245, 228));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(225, 245, 228));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(225, 245, 228));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        TOPICbox1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        TOPICbox1.setForeground(new java.awt.Color(0, 204, 102));
        TOPICbox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TOPICbox1.setText("TOPIC");
        TOPICbox1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Datebox1.setFont(new java.awt.Font("Leelawadee", 0, 10)); // NOI18N
        Datebox1.setForeground(new java.awt.Color(0, 204, 102));
        Datebox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Datebox1.setText("DD/MM/YYYY");
        Datebox1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel12.setBackground(new java.awt.Color(245, 255, 245));

        dayleftbox1.setFont(new java.awt.Font("STHupo", 0, 16)); // NOI18N
        dayleftbox1.setForeground(new java.awt.Color(255, 0, 0));
        dayleftbox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayleftbox1.setText("Days Left");
        dayleftbox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dayleftbox1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DayLeftBox1.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        DayLeftBox1.setForeground(new java.awt.Color(255, 0, 0));
        DayLeftBox1.setText("00");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DayLeftBox1)
                    .addComponent(dayleftbox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addComponent(DayLeftBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayleftbox1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(245, 255, 245));

        DayLeftBox2.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        DayLeftBox2.setForeground(new java.awt.Color(255, 102, 0));
        DayLeftBox2.setText("00");

        dayleftbox2.setFont(new java.awt.Font("STHupo", 0, 16)); // NOI18N
        dayleftbox2.setForeground(new java.awt.Color(255, 102, 0));
        dayleftbox2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayleftbox2.setText("Days Left");
        dayleftbox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dayleftbox2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayleftbox2)
                    .addComponent(DayLeftBox2))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(DayLeftBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayleftbox2)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(245, 255, 245));

        DayLeftBox3.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        DayLeftBox3.setForeground(new java.awt.Color(255, 204, 0));
        DayLeftBox3.setText("00");

        dayleftbox3.setFont(new java.awt.Font("STHupo", 0, 16)); // NOI18N
        dayleftbox3.setForeground(new java.awt.Color(255, 204, 0));
        dayleftbox3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayleftbox3.setText("Days Left");
        dayleftbox3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dayleftbox3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayleftbox3)
                    .addComponent(DayLeftBox3))
                .addGap(16, 16, 16))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(DayLeftBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayleftbox3)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        Datebox4.setFont(new java.awt.Font("Leelawadee", 0, 10)); // NOI18N
        Datebox4.setForeground(new java.awt.Color(0, 204, 102));
        Datebox4.setText("DD/MM/YYYY");

        jPanel17.setBackground(new java.awt.Color(245, 255, 245));

        DayLeftBox6.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        DayLeftBox6.setForeground(new java.awt.Color(225, 218, 218));
        DayLeftBox6.setText("00");

        dayleftbox6.setFont(new java.awt.Font("STHupo", 0, 16)); // NOI18N
        dayleftbox6.setForeground(new java.awt.Color(0, 204, 51));
        dayleftbox6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayleftbox6.setText("Days Left");
        dayleftbox6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dayleftbox6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayleftbox6)
                    .addComponent(DayLeftBox6))
                .addGap(16, 16, 16))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(DayLeftBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayleftbox6)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(245, 255, 245));

        DayLeftBox5.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        DayLeftBox5.setForeground(new java.awt.Color(225, 218, 218));
        DayLeftBox5.setText("00");

        dayleftbox5.setFont(new java.awt.Font("STHupo", 0, 16)); // NOI18N
        dayleftbox5.setForeground(new java.awt.Color(0, 102, 255));
        dayleftbox5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayleftbox5.setText("Days Left");
        dayleftbox5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dayleftbox5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayleftbox5)
                    .addComponent(DayLeftBox5))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(DayLeftBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayleftbox5)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(245, 255, 245));

        dayleftbox4.setFont(new java.awt.Font("STHupo", 0, 16)); // NOI18N
        dayleftbox4.setForeground(new java.awt.Color(0, 102, 255));
        dayleftbox4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayleftbox4.setText("Days Left");
        dayleftbox4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dayleftbox4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DayLeftBox4.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        DayLeftBox4.setForeground(new java.awt.Color(225, 218, 218));
        DayLeftBox4.setText("00");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DayLeftBox4)
                    .addComponent(dayleftbox4))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addComponent(DayLeftBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayleftbox4)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        TOPICbox4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        TOPICbox4.setForeground(new java.awt.Color(0, 204, 102));
        TOPICbox4.setText("TOPIC");

        TOPICbox2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        TOPICbox2.setForeground(new java.awt.Color(0, 204, 102));
        TOPICbox2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TOPICbox2.setText("TOPIC");
        TOPICbox2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Datebox2.setFont(new java.awt.Font("Leelawadee", 0, 10)); // NOI18N
        Datebox2.setForeground(new java.awt.Color(0, 204, 102));
        Datebox2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Datebox2.setText("DD/MM/YYYY");
        Datebox2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TOPICbox3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        TOPICbox3.setForeground(new java.awt.Color(0, 204, 102));
        TOPICbox3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TOPICbox3.setText("TOPIC");
        TOPICbox3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Datebox3.setFont(new java.awt.Font("Leelawadee", 0, 10)); // NOI18N
        Datebox3.setForeground(new java.awt.Color(0, 204, 102));
        Datebox3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Datebox3.setText("DD/MM/YYYY");
        Datebox3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Datebox6.setFont(new java.awt.Font("Leelawadee", 0, 10)); // NOI18N
        Datebox6.setForeground(new java.awt.Color(0, 204, 102));
        Datebox6.setText("DD/MM/YYYY");

        Datebox5.setFont(new java.awt.Font("Leelawadee", 0, 10)); // NOI18N
        Datebox5.setForeground(new java.awt.Color(0, 204, 102));
        Datebox5.setText("DD/MM/YYYY");

        TOPICbox6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        TOPICbox6.setForeground(new java.awt.Color(0, 204, 102));
        TOPICbox6.setText("TOPIC");

        TOPICbox5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        TOPICbox5.setForeground(new java.awt.Color(0, 204, 102));
        TOPICbox5.setText("TOPIC");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(TOPICbox1))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(Datebox1)))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(TOPICbox2))
                            .addComponent(Datebox2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(TOPICbox3)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(Datebox3)
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(TOPICbox4))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Datebox4)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(Datebox5))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(TOPICbox5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(TOPICbox6)
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(Datebox6)
                                        .addGap(18, 18, 18)))))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(TOPICbox1)
                            .addGap(1, 1, 1)
                            .addComponent(Datebox1))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(TOPICbox2)
                            .addGap(1, 1, 1)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Datebox2)
                                .addComponent(Datebox3))))
                    .addComponent(TOPICbox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(TOPICbox4)
                        .addGap(1, 1, 1)
                        .addComponent(Datebox4))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(TOPICbox5)
                            .addGap(1, 1, 1)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Datebox5)
                                .addComponent(Datebox6)))
                        .addComponent(TOPICbox6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        moreE.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moreE.setForeground(new java.awt.Color(0, 204, 51));
        moreE.setText("more");
        moreE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moreEMouseClicked(evt);
            }
        });

        moreD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moreD.setForeground(new java.awt.Color(0, 204, 51));
        moreD.setText("more");
        moreD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moreDMouseClicked(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(255, 248, 248));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 51));
        jLabel5.setText("Topic :");

        TopicEShow1.setForeground(new java.awt.Color(0, 102, 255));
        TopicEShow1.setText("Topic");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 51));
        jLabel6.setText("Date :");

        DateEShow1.setForeground(new java.awt.Color(0, 102, 255));
        DateEShow1.setText("DD/MM/YYYY");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TopicEShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(DateEShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TopicEShow1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DateEShow1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(245, 249, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Topic :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Date :");

        TopicEShow2.setForeground(new java.awt.Color(0, 102, 255));
        TopicEShow2.setText("Topic");

        DateEShow2.setForeground(new java.awt.Color(0, 102, 255));
        DateEShow2.setText("DD/MM/YYYY");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TopicEShow2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(DateEShow2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(TopicEShow2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateEShow2))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 253, 246));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setText("Date :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setText("Topic :");

        DateEShow3.setForeground(new java.awt.Color(0, 102, 255));
        DateEShow3.setText("DD/MM/YYYY");

        TopicEShow3.setForeground(new java.awt.Color(0, 102, 255));
        TopicEShow3.setText("Topic");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TopicEShow3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(DateEShow3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(TopicEShow3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateEShow3))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CMText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moreE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EventText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moreD))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMText)
                    .addComponent(moreE))
                .addGap(5, 5, 5)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventText)
                    .addComponent(moreD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moreEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moreEMouseClicked
        // TODO add your handling code here:
        ScheduleEvent Sevent = new ScheduleEvent(username);
        Sevent.setVisible(true);
        Sevent.pack();
        Sevent.setLocationRelativeTo(null);
        Sevent.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_moreEMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if(!settingVisible){
            setting = new SettingDialog(this,gmail,username,password,true);

            setting.setModalityType(Dialog.ModalityType.MODELESS);
            setting.setTitle("Non-modal Dialog");

            int x = this.getX() + 110;  // Adjust this value as needed
            int y = this.getY() + 30; // Adjust this value as needed
            setting.setLocation(x, y);

            setting.setVisible(true);
            settingVisible = true;

            setting.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    // Set the dialog visibility flag to false when the dialog is closed
                    settingVisible = false;
                }
            });
        } else {
            // If dialog is already visible, dispose it to close the dialog
            setting.dispose();
            settingVisible = false;
        }
        //this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        NotiFrame noti = new NotiFrame(gmail,username,password);
        noti.setVisible(true);
        noti.pack();
        noti.setLocationRelativeTo(null);
        noti.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if (!eordVisible) {
            // Create a new dialog if it's not already open
            eord = new EorDDialog(this, gmail,username,password, true);

            // Set the dialog as non-modal
            eord.setModalityType(Dialog.ModalityType.MODELESS);
            eord.setTitle("Non-modal Dialog");

            // Set size of the dialog to something more reasonable
            eord.setSize(70, 100);

            // Position the dialog
            int x = this.getX() + 125;  // Adjust this value as needed
            int y = this.getY() + 575; // Adjust this value as needed
            eord.setLocation(x, y);

            // Show the dialog
            eord.setVisible(true);
            refreshDayLeft();

            // Mark the dialog as visible
            eordVisible = true;

            // Handle dialog closing
            eord.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    // Set the dialog visibility flag to false when the dialog is closed
                    eordVisible = false;
                }
            });
        } else {
            // If dialog is already visible, dispose it to close the dialog
            eord.dispose();
            eordVisible = false;
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void moreDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moreDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_moreDMouseClicked

    private void EDayLeft() {
        File file = new File("Data/event.csv");
        if (!file.exists()) {
            updateDayLeftLabels(0, 0, 0, 0, 0, 0);
            updateTopicLabels("TOPIC", "TOPIC", "TOPIC", "TOPIC", "TOPIC", "TOPIC");
            updateDateLabels("DD/MM/YYYY", "DD/MM/YYYY", "DD/MM/YYYY", "DD/MM/YYYY", "DD/MM/YYYY", "DD/MM/YYYY");
            return;
        }
        
        class EventData {
            long daysLeft;
            String topic;
            String date;
            EventData(long daysLeft, String topic, String date) {
                      this.daysLeft = daysLeft;
                      this.topic = topic;
                      this.date = date;
            }
        }
        
         List<EventData> eventList = new ArrayList<>();

        //List<Map.Entry<Long, String>> dayTopicList = new ArrayList<>();
        //List<Map<String, Object>> eventList = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
             String line;
             LocalDate today = LocalDate.now();
             DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            while ((line = br.readLine()) != null) {
                    String[] parts = line.split(",");
                    if (parts.length >= 2) {
                    String topic = parts[0].trim();
                    String dateStr = parts[1].trim();
                    String[] dateRange = dateStr.split("-");
                    String startDateStr = dateRange[0].trim();
                    
                    try {
                         LocalDate eventDate = LocalDate.parse(startDateStr, formatter);
                         long daysLeft = ChronoUnit.DAYS.between(today, eventDate);

                        if (daysLeft >= 0) {
                            eventList.add(new EventData(daysLeft, topic, startDateStr));
                        } 
                    } catch (Exception e) {
                        System.out.println("Invalid date format in line: " + line);
                    }
                }
            }
        } catch (IOException e) {
                 e.printStackTrace();
        }

        eventList.sort(Comparator.comparingLong(e -> e.daysLeft));
        
        long[] days = new long[6];
        String[] topics = new String[6];
        String[] dates = new String[6];
        for (int i = 0; i < 6; i++) {
             if (i < eventList.size()) {
                 days[i] = eventList.get(i).daysLeft;
                 topics[i] = eventList.get(i).topic;
                 dates[i] = eventList.get(i).date;
             } else {
                 days[i] = 0;
                 topics[i] = "TOPIC";
                 dates[i] = "DD/MM/YYYY";
             }
        }

        SwingUtilities.invokeLater(() -> {
        updateDayLeftLabels(days[0], days[1], days[2], days[3], days[4], days[5]);
        updateTopicLabels(topics[0], topics[1], topics[2], topics[3], topics[4], topics[5]);
        updateDateLabels(dates[0], dates[1], dates[2], dates[3], dates[4], dates[5]);
        });
    }
    
    public void refreshDayLeft() {
        SwingUtilities.invokeLater(() -> {
        EDayLeft();
        DayLeftBox1.revalidate();
        DayLeftBox2.revalidate();
        DayLeftBox3.revalidate();
        DayLeftBox4.revalidate();
        DayLeftBox5.revalidate();
        DayLeftBox6.revalidate();
       
        DayLeftBox1.repaint();
        DayLeftBox2.repaint();
        DayLeftBox3.repaint();
        DayLeftBox4.repaint();
        DayLeftBox5.repaint();
        DayLeftBox6.repaint();
        
        
        });
    }

    private void updateDayLeftLabels(long d1, long d2, long d3,long d4, long d5, long d6) {
        DayLeftBox1.setText(String.format("%02d", d1));
        DayLeftBox2.setText(String.format("%02d", d2));
        DayLeftBox3.setText(String.format("%02d", d3));
        DayLeftBox4.setText(String.format("%02d", d4));
        DayLeftBox5.setText(String.format("%02d", d5));
        DayLeftBox6.setText(String.format("%02d", d6));
        
        
    }
    
    private void updateTopicLabels(String t1, String t2, String t3, String t4, String t5, String t6) {
        TOPICbox1.setText(t1);
        TOPICbox2.setText(t2);
        TOPICbox3.setText(t3);
        TOPICbox4.setText(t4);
        TOPICbox5.setText(t5);
        TOPICbox6.setText(t6);
        
        TopicEShow1.setText(t1);
        TopicEShow2.setText(t2);
        TopicEShow3.setText(t3);
    }
    
    private void updateDateLabels(String d1, String d2, String d3, String d4, String d5, String d6) {
        Datebox1.setText(d1);
        Datebox2.setText(d2);
        Datebox3.setText(d3);
        Datebox4.setText(d4);
        Datebox5.setText(d5);
        Datebox6.setText(d6);
        
        DateEShow1.setText(d1);
        DateEShow2.setText(d2);
        DateEShow3.setText(d3);
    }
    
    private LocalDate parseDate(String dateStr) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return LocalDate.parse(dateStr, formatter);
    }
    
    private void Notification() {
        ScheduledExecutorService scheduler = Executors.newSingleThreadScheduledExecutor();
        scheduler.scheduleAtFixedRate(() -> {
        int count = 0;
        List<String> notifyEvents = new ArrayList<>();

    try (BufferedReader br = new BufferedReader(new FileReader("Data/event.csv"))) {
        String line;
        DateTimeFormatter dateFmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter timeFmt = DateTimeFormatter.ofPattern("HH:mm");

        while ((line = br.readLine()) != null) {
            String[] parts = line.split(",");
            if (parts.length < 6) continue;

            String topic = parts[0].trim();
            String[] dateRange = parts[1].split("-");
            String[] timeRange = parts[2].split("-");

            LocalDate date = LocalDate.parse(dateRange[0].trim(), dateFmt);
            LocalTime startTime = LocalTime.parse(timeRange[0].trim(), timeFmt);
            LocalDateTime eventStart = LocalDateTime.of(date, startTime);

            int alarmValue = Integer.parseInt(parts[4].trim());
            String alarmUnit = parts[5].trim();

            LocalDateTime alarmTime = switch (alarmUnit) {
                case "Minute" -> eventStart.minusMinutes(alarmValue);
                case "Hour" -> eventStart.minusHours(alarmValue);
                case "Day" -> eventStart.minusDays(alarmValue);
                default -> eventStart;
            };

            LocalDateTime now = LocalDateTime.now();

            if (now.isAfter(alarmTime) && now.isBefore(eventStart)) {
                count++;
                notifyEvents.add(topic + " (" + eventStart.format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")) + ")");
            }
        }

    } catch (IOException e) {
        e.printStackTrace();
    }
    
    final int finalCount = count;

    SwingUtilities.invokeLater(() -> {
        System.out.println("Count to show: " + finalCount);
        //Noti.setText(String.format("%d", finalCount));
        //home.setNotifyList(notifyEvents);
    });

    }, 0, 1, TimeUnit.MINUTES);
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home("Gmail","Username","Password").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CMText;
    private javax.swing.JLabel DateEShow1;
    private javax.swing.JLabel DateEShow2;
    private javax.swing.JLabel DateEShow3;
    private javax.swing.JLabel Datebox1;
    private javax.swing.JLabel Datebox2;
    private javax.swing.JLabel Datebox3;
    private javax.swing.JLabel Datebox4;
    private javax.swing.JLabel Datebox5;
    private javax.swing.JLabel Datebox6;
    private javax.swing.JLabel DayLeftBox1;
    private javax.swing.JLabel DayLeftBox2;
    private javax.swing.JLabel DayLeftBox3;
    private javax.swing.JLabel DayLeftBox4;
    private javax.swing.JLabel DayLeftBox5;
    private javax.swing.JLabel DayLeftBox6;
    private javax.swing.JLabel EventText;
    private javax.swing.JLabel TOPICbox1;
    private javax.swing.JLabel TOPICbox2;
    private javax.swing.JLabel TOPICbox3;
    private javax.swing.JLabel TOPICbox4;
    private javax.swing.JLabel TOPICbox5;
    private javax.swing.JLabel TOPICbox6;
    private javax.swing.JLabel TopicEShow1;
    private javax.swing.JLabel TopicEShow2;
    private javax.swing.JLabel TopicEShow3;
    private javax.swing.JLabel dayleftbox1;
    private javax.swing.JLabel dayleftbox2;
    private javax.swing.JLabel dayleftbox3;
    private javax.swing.JLabel dayleftbox4;
    private javax.swing.JLabel dayleftbox5;
    private javax.swing.JLabel dayleftbox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel moreD;
    private javax.swing.JLabel moreE;
    // End of variables declaration//GEN-END:variables
}
