
import java.awt.Dialog;
import javax.swing.JDialog;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author user
 */
public class SettingDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SettingDialog.class.getName());
    private JFrame home;
    private String username;
    private String gmail ;
    private String password;
    private confirmLout lout;
    boolean loutVisible = false;
    /**
     * Creates new form SettingDialog
     * @param parent
     * @param Username
     * 
     * @param modal
     */
    public SettingDialog(JFrame parent, String Gmail, String Username, String Password, boolean modal) {
        super(parent, modal);
        this.home = parent;
        this.gmail = Gmail;
        this.password = Password;
        //System.out.println("Username in SettingDialog = " + username);
        this.username = Username ;
        
        initComponents();
        ShowUsername.setText(username);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProfilePanel = new javax.swing.JPanel();
        ProfileLabel = new javax.swing.JLabel();
        DialyPanel = new javax.swing.JPanel();
        Dialy = new javax.swing.JLabel();
        LogoutPanel = new javax.swing.JPanel();
        LogoutLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        UserText = new javax.swing.JLabel();
        ShowUsername = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 231));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));

        jLabel1.setFont(new java.awt.Font("STHupo", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 215, 62));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Setting");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ProfilePanel.setBackground(new java.awt.Color(227, 255, 227));
        ProfilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfilePanelMouseClicked(evt);
            }
        });

        ProfileLabel.setBackground(new java.awt.Color(0, 0, 0));
        ProfileLabel.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        ProfileLabel.setForeground(new java.awt.Color(255, 51, 0));
        ProfileLabel.setText("Profile");
        ProfileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ProfilePanelLayout = new javax.swing.GroupLayout(ProfilePanel);
        ProfilePanel.setLayout(ProfilePanelLayout);
        ProfilePanelLayout.setHorizontalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(ProfileLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProfilePanelLayout.setVerticalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProfileLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DialyPanel.setBackground(new java.awt.Color(61, 138, 255));
        DialyPanel.setForeground(new java.awt.Color(255, 255, 255));
        DialyPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DialyPanelMouseClicked(evt);
            }
        });

        Dialy.setBackground(new java.awt.Color(0, 0, 0));
        Dialy.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        Dialy.setForeground(new java.awt.Color(255, 255, 0));
        Dialy.setText("Dialy");
        Dialy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DialyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DialyPanelLayout = new javax.swing.GroupLayout(DialyPanel);
        DialyPanel.setLayout(DialyPanelLayout);
        DialyPanelLayout.setHorizontalGroup(
            DialyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialyPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Dialy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DialyPanelLayout.setVerticalGroup(
            DialyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dialy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LogoutPanel.setBackground(new java.awt.Color(255, 62, 62));
        LogoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseExited(evt);
            }
        });

        LogoutLabel.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        LogoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogoutLabel.setText("Log out");
        LogoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LogoutPanelLayout = new javax.swing.GroupLayout(LogoutPanel);
        LogoutPanel.setLayout(LogoutPanelLayout);
        LogoutPanelLayout.setHorizontalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(LogoutLabel)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        LogoutPanelLayout.setVerticalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoutLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 228));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        UserText.setFont(new java.awt.Font("STHupo", 0, 30)); // NOI18N
        UserText.setForeground(new java.awt.Color(0, 102, 255));
        UserText.setText("User");
        UserText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserTextMouseClicked(evt);
            }
        });

        ShowUsername.setFont(new java.awt.Font("STHupo", 0, 20)); // NOI18N
        ShowUsername.setForeground(new java.awt.Color(255, 153, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/ham.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(UserText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ShowUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(43, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(UserText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShowUsername)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DialyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LogoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(DialyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(LogoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutPanelMouseExited

    private void LogoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LogoutPanelMouseClicked

    private void LogoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLabelMouseClicked
        // TODO add your handling code here:
        if(!loutVisible){
        lout = new confirmLout(home,this,gmail,username,password,true);
        lout.setModalityType(Dialog.ModalityType.MODELESS);
        lout.setTitle("Non-modal Dialog");
        //confirmLout lout = new confirmLout(home,this,gmail,username,password,true);
        lout.setLocationRelativeTo(null);
        lout.setVisible(true);
        loutVisible = true;
        
        lout.addWindowListener(new java.awt.event.WindowAdapter() {
             @Override
             public void windowClosed(java.awt.event.WindowEvent e) {
             // Set the dialog visibility flag to false when the dialog is closed
             loutVisible = false;
             }
        });
        } else {
            // If dialog is already visible, dispose it to close the dialog
            lout.dispose();
            loutVisible = false;
        }
    }//GEN-LAST:event_LogoutLabelMouseClicked

    private void ProfileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileLabelMouseClicked
        // TODO add your handling code here:
        Profile profile = new Profile(gmail,username,password);
        profile.setVisible(true);
        profile.pack();
        profile.setLocationRelativeTo(null); //
        profile.setDefaultCloseOperation(JDialog.EXIT_ON_CLOSE);
        this.dispose();
        home.dispose();
    }//GEN-LAST:event_ProfileLabelMouseClicked

    private void ProfilePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilePanelMouseClicked
        // TODO add your handling code here:
        Profile profile = new Profile(gmail,username,password);
        profile.setVisible(true);
        profile.pack();
        profile.setLocationRelativeTo(null); //
        profile.setDefaultCloseOperation(JDialog.EXIT_ON_CLOSE);
        this.dispose();
        home.dispose();
    }//GEN-LAST:event_ProfilePanelMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        Profile profile = new Profile(gmail,username,password);
        profile.setVisible(true);
        profile.pack();
        profile.setLocationRelativeTo(null); //
        profile.setDefaultCloseOperation(JDialog.EXIT_ON_CLOSE);
        this.dispose();
        home.dispose();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void UserTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTextMouseClicked
        // TODO add your handling code here:
        Profile profile = new Profile(gmail,username,password);
        profile.setVisible(true);
        profile.pack();
        profile.setLocationRelativeTo(null); //
        profile.setDefaultCloseOperation(JDialog.EXIT_ON_CLOSE);
        this.dispose();
        home.dispose();
    }//GEN-LAST:event_UserTextMouseClicked

    private void DialyPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DialyPanelMouseClicked
        // TODO add your handling code here:
        /*AccInform acc = new AccInform(username);
        acc.setVisible(true);
        acc.pack();
        acc.setLocationRelativeTo(null); //
        acc.setDefaultCloseOperation(JDialog.EXIT_ON_CLOSE);
        this.dispose();
        home.dispose();*/
    }//GEN-LAST:event_DialyPanelMouseClicked

    private void DialyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DialyMouseClicked
        // TODO add your handling code here:
        Dialy dialy = new Dialy((Home) home,gmail,username,password);
        dialy.setVisible(true);
        dialy.pack();
        dialy.setLocationRelativeTo(null); //
        dialy.setDefaultCloseOperation(JDialog.EXIT_ON_CLOSE);
        this.dispose();
        home.dispose();
    }//GEN-LAST:event_DialyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                SettingDialog dialog = new SettingDialog(null,"Gmail","Username","Password",true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dialy;
    private javax.swing.JPanel DialyPanel;
    private javax.swing.JLabel LogoutLabel;
    private javax.swing.JPanel LogoutPanel;
    private javax.swing.JLabel ProfileLabel;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JLabel ShowUsername;
    private javax.swing.JLabel UserText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
